{"message":"Something went wrong, try again!","success":false,"response":{"traceback":"Traceback (most recent call last):\n  File \"/home/GetLinkBackend/helpers/utils/advice.py\", line 25, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/GetLinkBackend/talent_dashboard/views.py\", line 383, in get\n    cv_data = talent.cvdata.all()[0]\n              ~~~~~~~~~~~~~~~~~~~^^^\n  File \"/home/GetLinkBackend/venv/lib/python3.12/site-packages/django/db/models/query.py\", line 452, in __getitem__\n    return qs._result_cache[0]\n           ~~~~~~~~~~~~~~~~^^^\nIndexError: list index out of range\n"}}